### ISSUE TITLE
Design Issue

### ISSUE THREAD

**Issue by vv-monsalve** [googlefonts/oooh-baby#1]
## Google Fonts Latin Core & Plus coverage

- [x] Design all the glyphs required both in the [Latin Core](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/core_unique-glyphs.txt) + [GF Latin Plus encoding](https://github.com/googlefonts/gftools/blob/main/Lib/gftools/encodings/GF%20Glyph%20Sets/filter%20lists/nice%20names/plus_unique-glyphs.txt)
- [x] Create all the comb marks as mentioned below
- [x] Leave only the compound glyphs (e.g. `adblgrave`) marked in dark grey as pending to be created using the components

----

## Diacritics

- [x] Please ensure the definitive design is adjusted in the combining marks, so they will be ready to create the compound glyphs.
- [x] Once the definitive design is ensured in the `comb` marks Legacy marks, delete the legacy marks and add them back so they are made using the `comb` marks as components.
- [x] Diacritics need to be balanced (in weight, size, contrast) and match the style of the typeface design.
- [x] Adjust the vertical position using glyphs app locked guidelines.
- [x] Ensure related marks are consistent between them, e.g. `caron` and `circumflex`
- [x] Caron.alt need to have the alternate shape used in `Ľ` [Slovak](https://en.wikipedia.org/wiki/%C4%BD) On page 30 of [this document](http://theinsectsproject.eu/wp-content/uploads/2017/05/Insects-Project-2nd-edition_screen.pdf) you can find detailed info around the vertical Caron.
- [x] Leave a 0 sidebearings value for the marks

----
## Glyphs

- [x] The `ampersand` and `Eng` need to be consistent (in size and style) with the font. See [RUSerius](https://github.com/googlefonts/are-you-serious/issues/2#issuecomment-870693956) as reference
- [x] The German Double SS need to be fixed. This [article](https://www.lucasfonts.com/learn/1E9E) is a good reference
- [x] Currency symbols are related to the overall design and have balanced proportions
- [x] `ordfeminine` and `ordmasculine` as well as superior numbers are well proportioned and with a balanced stem thickness. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)
- [x] `fractions` and `superior` numerals have a good proportion + weight. [Issue of reference](https://github.com/googlefonts/cherish/issues/2#issuecomment-872268750)

----
## Spacing

- [x] Inspect the spacing and kerning of the font to ensure it is working properly and most common cases are covered. [Issue of reference](https://github.com/googlefonts/moondance/issues/1#issuecomment-940151753)
- [x] Terminal forms spacing should avoid crashes or collisions. [Issue of reference](https://github.com/googlefonts/comforter/issues/7)

**Comment by RobLeuschke** [comment]
This font is ready for review.

**Comment by crystaltype** [comment]
@vv-monsalve @RobLeuschke 
I noticed a lot of uppercase spacing issues for this typeface:
<img width="316" alt="Screen Shot 2021-11-13 at 04 14 53" src="https://user-images.githubusercontent.com/20129845/141535328-93ebe600-d084-49a7-85cd-a034934b8cdf.png">
<img width="321" alt="Screen Shot 2021-11-13 at 04 14 40" src="https://user-images.githubusercontent.com/20129845/141535332-102b5c9e-68cf-44dd-9242-7a19a873de3f.png">
<img width="347" alt="Screen Shot 2021-11-13 at 04 14 29" src="https://user-images.githubusercontent.com/20129845/141535336-66b1edc6-e2ec-4244-bc54-dabb014e28ca.png">
<img width="344" alt="Screen Shot 2021-11-13 at 04 14 15" src="https://user-images.githubusercontent.com/20129845/141535337-825c1e0f-0e5b-4672-a0d5-e43ff02ce62d.png">
<img width="334" alt="Screen Shot 2021-11-13 at 04 13 29" src="https://user-images.githubusercontent.com/20129845/141535340-8e760dde-4e89-491b-acd5-d0e8f018cd01.png">
<img width="353" alt="Screen Shot 2021-11-13 at 04 13 17" src="https://user-images.githubusercontent.com/20129845/141535342-1f847f1a-01a2-468a-ae8a-dad8bbb5f229.png">
<img width="170" alt="Screen Shot 2021-11-13 at 04 12 33" src="https://user-images.githubusercontent.com/20129845/141535346-59c8e58e-1916-497d-ad61-99e4d48673d4.png">
<img width="451" alt="Screen Shot 2021-11-13 at 04 12 13" src="https://user-images.githubusercontent.com/20129845/141535349-79331035-93fb-45d4-9ddb-7ca41021f1b4.png">
<img width="451" alt="Screen Shot 2021-11-13 at 04 06 39" src="https://user-images.githubusercontent.com/20129845/141534972-1ec135f2-93d2-4808-a1ef-bcb0b935e9aa.png">
<img width="306" alt="Screen Shot 2021-11-13 at 04 12 01" src="https://user-images.githubusercontent.com/20129845/141535319-69a977b7-7236-418b-9f84-230d8f19a9cc.png">

(Please wait for Viviana's before trying to fix these issues, thanks a lot!)

**Comment by vv-monsalve** [comment]
@crystaltype Thanks for reporting this.

@RobLeuschke While perhaps capitalizing is not the primary intended use for Oooh Baby, given its caps are more roman than really cursive, I think it would be possible even for short expressions. In those cases, the spacing should be functional. Here you can see the [Browsers Preview Issue](https://github.com/googlefonts/oooh-baby/issues/6)

<img width="1012" alt="Screen Shot 2021-11-12 at 17 25 18" src="https://user-images.githubusercontent.com/48698976/141547326-d877e2ad-1cb9-4575-8a61-3a927ccfbe02.png">

I've already updated the source file in DropBox, please look for the pink Uper&Lower case as a hint of it being the latest file, please use that one to review and solve the spacing.

**Comment by RobLeuschke** [comment]
I have addressed the issue of capital spacing and kerning. I think the texture of text is working. I am not concerned about being strict with it as it really isn't designed to be used in all caps. Let me know if you still see things that need to be addressed. 
![image](https://user-images.githubusercontent.com/57553693/141672377-c91450ac-36df-4cd8-947b-0541a3ddef00.png)

**Comment by RobLeuschke** [comment]
The connectors for this font are not as critical as in other more formal connecting scripts. Having said that, I have addressed those forms that do connect, particularly the 'c' and 'e.'

![image](https://user-images.githubusercontent.com/57553693/141673637-56c3d1ec-fc27-4f82-b915-7c0aeeb3c322.png)

**Comment by RobLeuschke** [comment]
@vv-monsalve Please review the file in Dropbox and let me know if there are any other issues that need my attention.
R
